import {engines,engineById} from './engines.mjs';
import {createSnapshotAPI} from './snapshot.mjs';
const $=id=>document.getElementById(id);
const read=createSnapshotAPI({url:new URL('./data/dashboard.json',location.href).href});
let controller;
let articleLimit=30;
const node=(tag,text,className)=>{const el=document.createElement(tag);if(text!=null)el.textContent=text;if(className)el.className=className;return el;};
const safeURL=value=>{try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)?url.href:null;}catch{return null;}};
const number=value=>Number.isFinite(value)?value.toLocaleString('pt-BR'):'—';
const date=value=>value && Number.isFinite(Date.parse(value))?new Date(value).toLocaleString('pt-BR'):'Data não informada';
function empty(title,message){const card=node('div',null,'card empty');card.append(node('h2',title),node('p',message));$('results').replaceChildren(card);}
function translationLink(a, wholeArticle=false){const url=new URL('https://translate.google.com/');url.searchParams.set('sl','auto');url.searchParams.set('tl','pt');if(wholeArticle){url.pathname='/translate';url.searchParams.set('u',a.url);url.searchParams.set('op','websites');}else{url.searchParams.set('text',[a.title,a.summary].filter(Boolean).join('\n\n'));url.searchParams.set('op','translate');}const link=external(url.href,wholeArticle?'Ler fonte em português':'Traduzir título');link.className='btn translation-link';link.title='Tradução automática pelo Google Tradutor — abre em outra aba';return link;}
function external(url,label){const a=node('a',label);a.href=safeURL(url)||'#';a.target='_blank';a.rel='noopener noreferrer';return a;}
async function reader(id){const dialog=$('reader');$('reader-content').replaceChildren(node('p','Carregando matéria…'));dialog.showModal();try{const response=await read(`articles/${encodeURIComponent(id)}`);const a=response.data;const el=$('reader-content');el.replaceChildren(node('h2',a.title,'reader-title'),node('p',a.text_basis==='extracted_page'?'Texto extraído da página':'Leitura no veículo de origem','meta'),node('div',a.text||a.summary||'Texto indisponível.','reading-body'));if(safeURL(a.url))el.append(external(a.url,'Abrir fonte original'),translationLink(a,true));}catch{$('reader-content').replaceChildren(node('p','Não foi possível carregar a matéria. Tente novamente.'));}}
function articles(data){if(!data.items?.length)return empty('Nenhuma matéria disponível','Nenhum resultado neste recorte das 2.000 matérias mais recentes. Ajuste os filtros.');const grid=node('div',null,'article-grid');for(const a of data.items){const card=node('article',null,'card article');const top=node('div',null,'article-top');const country=node('span',a.country||'Origem não informada','country-badge');country.title='País de origem do veículo';top.append(node('span',a.source,'meta'),country);card.append(top,node('div',date(a.published_at),'meta'),node('h2',a.title),node('p',a.summary||''));const actions=node('div',null,'actions');actions.append(translationLink(a));if(a.id!=null){const button=node('button','Ler matéria','btn');button.type='button';button.addEventListener('click',()=>reader(a.id));actions.append(button);}if(safeURL(a.url))actions.append(external(a.url,'Fonte original'));card.append(actions);grid.append(card);}$('results').replaceChildren(grid);const count=node('p',`Exibindo ${data.items.length} de ${data.total??data.items.length} matérias neste recorte.`,'coverage');$('results').append(count);if(data.items.length<data.total){const more=node('button','Mostrar mais matérias','btn');more.type='button';more.addEventListener('click',()=>{articleLimit+=30;render();});$('results').append(more);}}
function table(headers,rows){const wrap=node('div',null,'card table-wrap');const t=node('table');const head=node('thead');const line=node('tr');headers.forEach(v=>line.append(node('th',v)));head.append(line);const body=node('tbody');rows.forEach(values=>{const tr=node('tr');values.forEach(v=>tr.append(node('td',String(v??'—'))));body.append(tr);});t.append(head,body);wrap.append(t);return wrap;}
function trends(data){if(!data.items?.length)return empty('Aguardando os primeiros resultados','Os temas serão apresentados com a quantidade de matérias e veículos que falaram sobre eles.');$('results').replaceChildren(table(['Assunto','Local','Matérias','Veículos'],data.items.map(t=>[t.label,t.place,number(t.articles),number(t.publishers)])));}
function operations(data){if(!data.metrics)return empty('Cobertura ainda não disponível','A contagem da coleta será exibida aqui após conectar o painel.');const grid=node('div',null,'metric-grid');for(const [key,label] of Object.entries({feeds_attempted:'Feeds tentados',feeds_ok:'Feeds lidos',feeds_errors:'Feeds com erro',articles:'Notícias únicas',extracted:'Textos extraídos',pending:'Extrações pendentes',rss_texts:'Textos fornecidos pelos RSS',extraction_errors:'Falhas de extração'})){const card=node('div',null,'card metric');card.append(node('span',label),node('strong',number(data.metrics[key])));grid.append(card);}$('results').replaceChildren(grid);if(data.errors?.length)$('results').append(table(['Veículo','País','Erro'],data.errors.map(r=>[r.name,r.country,r.error])));}
async function render(){controller?.abort();controller=new AbortController();const engine=engineById(location.hash.slice(1));$('title').textContent=engine.label;$('description').textContent=engine.description;document.querySelectorAll('nav a').forEach(a=>{if(a.hash==='#'+engine.id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('filters').hidden=engine.id==='operations';$('article-filters').hidden=engine.id!=='articles';$('trend-filters').hidden=engine.id!=='trends';$('place-filter').hidden=engine.id==='trends' && $('scope').value==='globe';$('coverage').textContent='';$('results').setAttribute('aria-busy','true');empty('Buscando dados','');const params=engine.id==='operations'?{}:engine.id==='trends'?{scope:$('scope').value,place:$('scope').value==='globe'?'':$('place').value.trim()}:{q:$('search').value.trim(),place:$('place').value.trim(),limit:articleLimit};try{const response=await read(engine.endpoint,params,controller.signal);$('coverage').textContent=`Atualização: ${date(response.as_of)}${response.status==='partial'?' · Cobertura parcial':''}${engine.id==='trends'?' · Janela de 24h · Revisão editorial pendente':''}${engine.id==='articles'?' · Até 2.000 matérias recentes':''}`;if(response.status==='building')empty('Análise em andamento','Os resultados aparecerão depois que esta execução terminar.');else if(['unavailable','failed'].includes(response.status))empty('Resultados indisponíveis','Consulte a área de coleta para verificar a cobertura.');else ({articles,trends,operations}[engine.view])(response.data);}catch(error){if(error.name==='AbortError')return;empty(error.code==='not_connected'?'Painel em preparação':'Não foi possível carregar os dados',error.code==='not_connected'?'As áreas estão organizadas. Estamos preparando a conexão dos motores antes da publicação.':'Tente atualizar novamente.');}finally{$('results').setAttribute('aria-busy','false');}}
for(const engine of engines){const a=node('a',engine.label);a.href='#'+engine.id;$('engines').append(a);}
$('filters').addEventListener('submit',event=>{event.preventDefault();articleLimit=30;render();});$('scope').addEventListener('change',render);$('refresh').addEventListener('click',render);$('close-reader').addEventListener('click',()=>$('reader').close());window.addEventListener('hashchange',render);render();

setInterval(()=>{if(!document.hidden)render();},60000);
