import {engines,engineById} from './engines.mjs';
import {createAPI} from './api.mjs';
const $=id=>document.getElementById(id);
const read=createAPI({base:new URL('./api/',location.href).href});
let controller;
const node=(tag,text,className)=>{const el=document.createElement(tag);if(text!=null)el.textContent=text;if(className)el.className=className;return el;};
const safeURL=value=>{try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)?url.href:null;}catch{return null;}};
const number=value=>Number.isFinite(value)?value.toLocaleString('pt-BR'):'—';
const date=value=>value && Number.isFinite(Date.parse(value))?new Date(value).toLocaleString('pt-BR'):'Data não informada';
function empty(title,message){const card=node('div',null,'card empty');card.append(node('h2',title),node('p',message));$('results').replaceChildren(card);}
function external(url,label){const a=node('a',label);a.href=safeURL(url)||'#';a.target='_blank';a.rel='noopener noreferrer';return a;}
async function reader(id){const dialog=$('reader');$('reader-content').replaceChildren(node('p','Carregando matéria…'));dialog.showModal();try{const response=await read(`articles/${encodeURIComponent(id)}`);const a=response.data;const el=$('reader-content');el.replaceChildren(node('h2',a.title,'reader-title'),node('p',a.text_basis==='extracted_page'?'Texto extraído da página':'Resumo disponível','meta'),node('div',a.text||a.summary||'Texto indisponível.','reading-body'));if(safeURL(a.url))el.append(external(a.url,'Abrir fonte original'));}catch{$('reader-content').replaceChildren(node('p','Não foi possível carregar a matéria. Tente novamente.'));}}
function articles(data){if(!data.items?.length)return empty('Nenhuma matéria disponível','As matérias aparecerão aqui quando esta área estiver conectada à base.');const grid=node('div',null,'article-grid');for(const a of data.items){const card=node('article',null,'card article');card.append(node('div',[a.source,a.country,date(a.published_at)].filter(Boolean).join(' · '),'meta'),node('h2',a.title),node('p',a.summary||''));const actions=node('div',null,'actions');if(a.id!=null){const button=node('button','Ler matéria','btn');button.type='button';button.addEventListener('click',()=>reader(a.id));actions.append(button);}if(safeURL(a.url))actions.append(external(a.url,'Fonte original'));card.append(actions);grid.append(card);}$('results').replaceChildren(grid);}
function table(headers,rows){const wrap=node('div',null,'card table-wrap');const t=node('table');const head=node('thead');const line=node('tr');headers.forEach(v=>line.append(node('th',v)));head.append(line);const body=node('tbody');rows.forEach(values=>{const tr=node('tr');values.forEach(v=>tr.append(node('td',String(v??'—'))));body.append(tr);});t.append(head,body);wrap.append(t);return wrap;}
function trends(data){if(!data.items?.length)return empty('Aguardando os primeiros resultados','Os temas serão apresentados com a quantidade de matérias e veículos que falaram sobre eles.');$('results').replaceChildren(table(['Assunto','Local','Matérias','Veículos'],data.items.map(t=>[t.label,t.place,number(t.articles),number(t.publishers)])));}
function operations(data){if(!data.metrics)return empty('Cobertura ainda não disponível','A contagem da coleta será exibida aqui após conectar o painel.');const grid=node('div',null,'metric-grid');for(const [key,label] of Object.entries({feeds_attempted:'Feeds tentados',feeds_ok:'Feeds lidos',feeds_errors:'Feeds com erro',articles:'Notícias únicas',extracted:'Textos extraídos',pending:'Extrações pendentes'})){const card=node('div',null,'card metric');card.append(node('span',label),node('strong',number(data.metrics[key])));grid.append(card);}$('results').replaceChildren(grid);if(data.errors?.length)$('results').append(table(['Veículo','País','Erro'],data.errors.map(r=>[r.name,r.country,r.error])));}
async function render(){controller?.abort();controller=new AbortController();const engine=engineById(location.hash.slice(1));$('title').textContent=engine.label;$('description').textContent=engine.description;document.querySelectorAll('nav a').forEach(a=>{if(a.hash==='#'+engine.id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('filters').hidden=engine.id==='operations';$('article-filters').hidden=engine.id!=='articles';$('trend-filters').hidden=engine.id!=='trends';$('place-filter').hidden=engine.id==='trends' && $('scope').value==='globe';$('coverage').textContent='';$('results').setAttribute('aria-busy','true');empty('Buscando dados','');const params=engine.id==='operations'?{}:engine.id==='trends'?{scope:$('scope').value,place:$('scope').value==='globe'?'':$('place').value.trim()}:{q:$('search').value.trim(),place:$('place').value.trim(),limit:30};try{const response=await read(engine.endpoint,params,controller.signal);$('coverage').textContent=`Atualização: ${date(response.as_of)}${response.status==='partial'?' · Cobertura parcial':''}`;if(response.status==='building')empty('Análise em andamento','Os resultados aparecerão depois que esta execução terminar.');else if(['unavailable','failed'].includes(response.status))empty('Resultados indisponíveis','Consulte a área de coleta para verificar a cobertura.');else ({articles,trends,operations}[engine.view])(response.data);}catch(error){if(error.name==='AbortError')return;empty(error.code==='not_connected'?'Painel em preparação':'Não foi possível carregar os dados',error.code==='not_connected'?'As áreas estão organizadas. Estamos preparando a conexão dos motores antes da publicação.':'Tente atualizar novamente.');}finally{$('results').setAttribute('aria-busy','false');}}
for(const engine of engines){const a=node('a',engine.label);a.href='#'+engine.id;$('engines').append(a);}
$('filters').addEventListener('submit',event=>{event.preventDefault();render();});$('scope').addEventListener('change',render);$('refresh').addEventListener('click',render);$('close-reader').addEventListener('click',()=>$('reader').close());window.addEventListener('hashchange',render);render();
