const $=id=>document.getElementById(id);
const base=new URL('./data/explorer/',location.href);
const n=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=String(text);if(cls)e.className=cls;return e;};
const num=v=>Number(v||0).toLocaleString('pt-BR');
const date=v=>v?new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Sem data';
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const sourceContinent=s=>s.country==='Egito'?'África':['Rússia','Turquia'].includes(s.country)?'Europa/Ásia (transcontinental)':({'América do Norte':'América do Norte','América Central e Caribe':'América do Norte','América do Sul':'América do Sul','Europa Ocidental':'Europa','Europa Oriental (Leste Europeu)':'Europa','Ásia (Leste Asiático e Sudeste Asiático)':'Ásia','Oriente Médio':'Ásia','África':'África','Oceania':'Oceania'}[s.region]||'Não mapeado');
const memo=new Map();
async function get(file){if(!memo.has(file))memo.set(file,fetch(new URL(file,base)).then(r=>{if(!r.ok)throw Error('Falha ao carregar '+file);return r.json();}).catch(e=>{memo.delete(file);throw e;}));return memo.get(file);}
function link(url,label){const a=n('a',label,'btn');try{const u=new URL(url,location.href);if(!['http:','https:'].includes(u.protocol))return n('span',label);a.href=u.href;}catch{return n('span',label);}a.target='_blank';a.rel='noopener noreferrer';return a;}
function download(file,label='Baixar dados deste recorte'){const a=link(new URL(file,base).href,label);a.download=file.split('/').pop();return a;}
function button(label,fn){const b=n('button',label,'btn');b.type='button';b.onclick=fn;return b;}
function raw(value){const d=n('details');d.append(n('summary','Dados e critérios completos'));d.append(n('pre',JSON.stringify(value,null,2)));return d;}
function metrics(values){const grid=n('div',null,'metric-grid');for(const [label,v] of values){const c=n('div',null,'card metric');c.append(n('span',label),n('strong',typeof v==='number'?num(v):v));grid.append(c);}return grid;}
function notice(text){return n('p',text,'notice');}
let m,articles=[],byId=new Map(),version=0,page=0;
const sections={overview:['Visão geral','Tudo o que já foi coletado e processado'],articles:['Todas as matérias','Base inteira, textos disponíveis e fontes de origem'],daily:['Fechamento diário','Contabilidade, pautas e republicações por país, continente e mundo'],crossings:['Cruzamentos','Cobertura geográfica das pautas e evidências de similaridade'],trends:['Tendências e análises','Histórico completo das análises semânticas disponíveis'],operations:['Coleta e erros','Execuções, cobertura e falhas registradas']};
const state={q:'',place:'',scope:'globe',from:'',to:'',content:'all',inventory:'all',closure:'',run:'',kind:'subjects'};
function select(label,items,value,fn){const box=n('label',label);const s=n('select',null,'form-select');for(const [v,t] of items){const o=n('option',t);o.value=v;s.append(o);}s.value=value;s.onchange=()=>{fn(s.value);page=0;render();};box.append(s);return box;}
function input(label,key,type='search'){const box=n('label',label),i=n('input',null,'form-control');i.type=type;i.value=state[key];i.onchange=()=>{state[key]=i.value;page=0;render();};i.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();i.blur();}};box.append(i);return box;}
function scopeControls(bar){bar.append(select('Abrangência',[['globe','Mundo'],['continent','Continente'],['country','País']],state.scope,v=>{state.scope=v;state.place='';}),input('Filtrar local','place'));}
function closureControls(bar){const options=m.closures.map(c=>[c.id,`${c.day} · ${c.mode==='closed'?'Fechamento':'Prévia'} · ${date(c.cutoff)}`]);if(!state.closure)state.closure=m.closures.find(c=>c.mode==='closed')?.id||options[0]?.[0]||'';bar.append(select('Dia / processamento',options,state.closure,v=>state.closure=v));}
function pageList(rows,draw,target=$('results')){const count=n('p',`${num(rows.length)} resultados · página ${page+1} de ${Math.max(1,Math.ceil(rows.length/30))}`,'coverage');const nav=n('div',null,'actions');if(page>0)nav.append(button('← Anterior',()=>{page--;render();}));if((page+1)*30<rows.length)nav.append(button('Próxima →',()=>{page++;render();}));target.append(count,nav);const grid=n('div',null,'article-grid');rows.slice(page*30,(page+1)*30).forEach(r=>grid.append(draw(r)));target.append(grid,nav.cloneNode(false));}
function translate(a){const u=new URL('https://translate.google.com/');u.search=new URLSearchParams({sl:'auto',tl:'pt',text:a.title||'',op:'translate'});return link(u,'Traduzir título');}
function articleCard(a){const card=n('article',null,'card article');const top=n('div',null,'article-top');top.append(n('span',a.source||a.sources?.map(s=>s.name).join(', '),'meta'),n('span',a.country||a.sources?.map(s=>s.country).join(', '),'country-badge'));card.append(top,n('span',date(a.published_at||a.first_seen_at),'meta'),n('h2',a.title),n('p',a.summary||''));const actions=n('div',null,'actions');actions.append(button(a.has_text?'Ler texto disponível':'Abrir matéria',()=>reader(a.id)),translate(a),link(a.url,'Fonte'));card.append(actions);return card;}
async function reader(id){const a=byId.get(String(id));const d=$('reader');if(!d.open)d.showModal();const el=$('reader-content');el.replaceChildren(n('p','Carregando texto…'));if(!a){el.replaceChildren(notice('Esta referência histórica não consta no cadastro atual. Consulte o link da evidência.'));return;}try{const texts=await get(a.text_file);const b=texts[String(id)];el.replaceChildren(n('h2',a.title),n('p',`${a.source} · ${a.country} · ${date(a.published_at)}`,'meta'),notice(b.text_basis==='publisher_rss'?'Conteúdo fornecido pelo RSS do veículo.':b.text?'Texto extraído automaticamente. Pode conter lacunas; confira a fonte.':'Texto indisponível. Exibindo o resumo disponível.'),n('div',b.text||b.summary||'Sem texto ou resumo disponível.','reading-body'),link(a.url,'Fonte original'),translate(a),raw(a));const u=new URL('https://translate.google.com/translate');u.search=new URLSearchParams({sl:'auto',tl:'pt',u:a.url});el.append(link(u,'Ler fonte em português'));}catch(e){el.replaceChildren(notice(e.message),link(a.url,'Fonte original'));}}
function evidence(group,ids,details={}){const d=$('reader');if(!d.open)d.showModal();const el=$('reader-content');el.replaceChildren(n('h2',group),notice(`${num(ids.length)} matérias vinculadas. Abra cada texto para conferir.`));for(const id of ids){const a=byId.get(String(id));if(!a){el.append(n('p',`Referência histórica ${id}`));continue;}const row=n('div',null,'evidence-row');row.append(button(a.title,()=>reader(id)),n('p',`${a.country} · ${a.source}`,'meta'),link(a.url,'Fonte original'));el.append(row);}el.append(raw(details));}
function groupCard(r,key='article_ids'){const ids=r[key]||[];const c=n('article',null,'card article');c.append(n('span',r.place||'Mundo','country-badge'),n('h2',r.label||r.topic_label||r.subject_id),n('p',`${num(r.publications??ids.length)} publicações · ${num(r.publishers)} veículos`));if(r.countries)c.append(n('p',r.countries.join(' · '),'meta'));c.append(button('Ver todas as matérias e evidências',()=>evidence(r.label,ids,r)));return c;}
function within(a){const day=(a.published_at||a.first_seen_at||'').slice(0,10);return (!state.from||day>=state.from)&&(!state.to||day<=state.to);}
async function render(){if(!m)return;const ticket=++version;const section=sections[location.hash.slice(1)]?location.hash.slice(1):'overview';$('title').textContent=sections[section][0];$('description').textContent=sections[section][1];document.querySelectorAll('nav a').forEach(a=>a.setAttribute('aria-current',a.hash==='#'+section?'page':'false'));const bar=$('controls');bar.replaceChildren();const out=$('results');out.replaceChildren(notice('Carregando recorte…'));$('coverage').textContent=`Atualização ${date(m.generated_at)} (Brasília) · ${num(m.total_articles)} matérias no cadastro · sem corte de 2.000`;
try{
if(section==='overview'){out.replaceChildren(metrics([['Matérias no cadastro',m.total_articles],['Com texto acessível',articles.filter(a=>a.has_text).length],['Análises registradas',m.analyses.length],['Fechamentos e prévias',m.closures.length],['Feeds funcionando',m.operations.data.metrics.feeds_ok],['Feeds com erro',m.operations.data.metrics.feeds_errors]]));const grid=n('div',null,'article-grid');for(const [id,[title,desc]] of Object.entries(sections).filter(([id])=>id!=='overview')){const c=n('div',null,'card article');const a=n('a',title);a.href='#'+id;c.append(n('h2'),a,n('p',desc));grid.append(c);}out.append(grid,notice('Disponíveis: coleta, textos, análises de 24h, fechamento diário, republicações e comparação geográfica dos grupos. Grafo Rua × Elite, redação, SEO e acompanhamento de 7/15/30 dias ainda não estão implementados.'),notice('Os agrupamentos são estimativas automáticas, com revisão editorial pendente. Similaridade não é probabilidade de cópia.'),raw({export_errors:m.export_errors}));}
if(section==='articles'){bar.append(input('Buscar título, resumo ou veículo','q'),input('País / origem','place'),input('Desde','from','date'),input('Até','to','date'),select('Texto',[['all','Todos'],['yes','Com texto'],['no','Sem texto']],state.content,v=>state.content=v),select('Inventário',[['all','Atual + histórico'],['active','Fontes atuais'],['history','Somente histórico']],state.inventory,v=>state.inventory=v));const rows=articles.filter(a=>norm([a.title,a.summary,a.source].join(' ')).includes(norm(state.q))&&norm(a.country).includes(norm(state.place))&&within(a)&&(state.content==='all'||a.has_text===(state.content==='yes'))&&(state.inventory==='all'||a.active===(state.inventory==='active')));out.replaceChildren(notice('Inclui registros históricos e datas futuras, identificadas na própria matéria. Os filtros percorrem a base inteira.'));pageList(rows,articleCard);}
if(section==='daily'||section==='crossings'){closureControls(bar);scopeControls(bar);bar.append(input('Buscar pauta','q'));const c=m.closures.find(c=>c.id===state.closure);if(!c?.scopes){out.replaceChildren(notice(c?.error?'Relatório indisponível: '+c.error:'Nenhum fechamento disponível.'));return;}const rows=await get(c.scopes[state.scope]);if(ticket!==version)return;const places=Object.entries(rows).filter(([place])=>norm(place).includes(norm(state.place)));out.replaceChildren(notice(`${c.day} · ${c.mode==='closed'?'Dia fechado':'Prévia'} · revisão editorial pendente${c.coverage?.observation_history_complete?'':' · histórico de reaparições incompleto'}`));const tools=n('div',null,'actions');tools.append(download(c.download,'Baixar relatório completo (.json.gz)'),download(c.scopes[state.scope]),button('Critérios e cobertura',()=>{const d=$('reader');if(!d.open)d.showModal();$('reader-content').replaceChildren(raw(c.coverage));}));out.append(tools);
if(section==='daily'){bar.append(select('Visualização',[['subjects','Pautas / assuntos'],['copies','Republicações'],['totals','Contabilidade por local']],state.kind,v=>state.kind=v));if(state.kind==='totals'){const wrap=n('div',null,'card table-wrap'),t=n('table');const h=n('tr');['Local','Publicações','Textos distintos estimados','Cópias adicionais','Aparições'].forEach(x=>h.append(n('th',x)));t.append(h);for(const [p,r] of places){const tr=n('tr');[p,r.publications,r.distinct_texts_estimated,r.extra_copies_estimated,r.feed_sightings_all_articles].forEach(x=>tr.append(n('td',typeof x==='number'?num(x):x)));t.append(tr);}wrap.append(t);out.append(wrap);}else{const ranks=places.flatMap(([place,r])=>(r[state.kind==='copies'?'ranking':'subject_ranking']||[]).map(x=>({...x,place}))).filter(r=>norm(r.label).includes(norm(state.q))&&(state.kind!=='copies'||r.publications>1));ranks.sort((a,b)=>b.publications-a.publications);pageList(ranks,groupCard);}}
else{const ranks=places.flatMap(([place,r])=>(r.subject_ranking||[]).map(x=>({...x,place}))).filter(r=>r.publications>1&&norm(r.label).includes(norm(state.q))).map(r=>{const countries=new Map();for(const id of r.article_ids){const a=byId.get(String(id));for(const country of new Set((a?.sources||[]).map(s=>s.country))){countries.set(country,(countries.get(country)||0)+1);}}return {...r,countries:[...countries].map(([p,total])=>`${p}: ${total}`),country_count:countries.size};}).sort((a,b)=>b.country_count-a.country_count||b.publications-a.publications);out.append(notice('Cada linha compara a presença de uma mesma pauta nos países das fontes monitoradas. Ausência nesta base não prova silêncio da mídia.'));pageList(ranks,groupCard);const pairs=await get(c.pairs);if(ticket!==version)return;out.append(button(`Abrir ${num(pairs.length)} comparações entre textos`,()=>pairView(pairs)),download(c.pairs,'Baixar todas as comparações'));}}
if(section==='trends'){const options=m.analyses.map(r=>[r.id,`${date(r.finished_at)} · ${r.status} · ${r.id}`]);if(!state.run)state.run=m.analyses.find(r=>r.file&&r.coverage?.editorial_status!=='rejected_by_review')?.id||options[0]?.[0];bar.append(select('Execução',options,state.run,v=>state.run=v));scopeControls(bar);bar.append(input('Buscar assunto','q'));const run=m.analyses.find(r=>r.id===state.run);if(!run?.file){out.replaceChildren(notice('Esta execução não tem relatório final disponível.'),raw(run));return;}const payload=await get(run.file);if(ticket!==version)return;const group=new Map();for(const a of payload.articles||[]){const local=new Map();for(const source of a.sources||[]){const place=state.scope==='globe'?'Mundo':state.scope==='country'?source.country:sourceContinent(source);if(state.scope!=='globe'&&!norm(place).includes(norm(state.place)))continue;if(!local.has(place))local.set(place,[]);local.get(place).push(source);}for(const [place,sources] of local){const key=place+'|'+a.topic_id;if(!group.has(key))group.set(key,{label:a.topic_id==='outlier'?'Matérias sem agrupamento':a.topic_label,article_ids:[],countries:new Set(),publishers:new Set(),place});const g=group.get(key);g.article_ids.push(a.id);sources.forEach(s=>{g.countries.add(s.country);g.publishers.add(s.site_url||s.name);});}}const ranks=[...group.values()].map(g=>({...g,countries:[...g.countries],publishers:g.publishers.size,publications:g.article_ids.length})).filter(g=>norm(g.label).includes(norm(state.q))).sort((a,b)=>b.publications-a.publications);out.replaceChildren(notice(`Janela de ${payload.window_hours||24} horas · ${run.coverage?.editorial_status==='rejected_by_review'?'REPROVADO na revisão — preservado para auditoria':'Revisão editorial pendente'}`),download(run.file,'Baixar análise completa'),raw(payload.coverage));for(const key of ['cluster-audit','corpus'])if(run[key])out.append(download(run[key],key==='cluster-audit'?'Baixar auditoria de todos os grupos':'Baixar auditoria do corpus'));pageList(ranks,groupCard);}
if(section==='operations'){out.replaceChildren(metrics(Object.entries(m.operations.data.metrics).map(([k,v])=>[{feeds_attempted:'Feeds tentados',feeds_ok:'Feeds OK',feeds_errors:'Feeds com erro',articles:'Notícias ativas',extracted:'Textos das páginas',pending:'Pendentes',rss_texts:'Textos dos RSS',extraction_errors:'Falhas de extração'}[k]||k,v])),notice('Uma execução encerrada pode conter falhas de feeds ou de extração.'),raw(m.operations.data.errors));const attempts=await get(m.attempts);if(ticket!==version)return;out.append(download(m.attempts,'Baixar histórico da coleta'));pageList(attempts,a=>{const c=n('div',null,'card article');c.append(n('h2',date(a.finished_at)),n('p',`Janela ${date(a.slot)} · ${a.report.status}`),link(`https://github.com/zehlima/blog-criia-rss/actions/runs/${a.id}`,'Ver execução'),raw(a.report));return c;});}
}catch(e){if(ticket===version)out.replaceChildren(notice(e.message),button('Tentar novamente',render));}}
function pairView(pairs){const d=$('reader');if(!d.open)d.showModal();const el=$('reader-content');let p=0;const draw=()=>{el.replaceChildren(n('h2','Comparações entre textos'),notice('Os índices medem similaridade. Não são probabilidades calibradas de republicação.'));const nav=n('div',null,'actions');if(p)nav.append(button('Anterior',()=>{p--;draw();}));if((p+1)*30<pairs.length)nav.append(button('Próximas comparações',()=>{p++;draw();}));el.append(nav,n('p',`Página ${p+1} · ${num(pairs.length)} pares`));for(const x of pairs.slice(p*30,(p+1)*30)){const row=n('div',null,'evidence-row');row.append(n('strong',({duplicate:'Cópia estimada',possible_republication:'Possível republicação — revisar',same_subject_candidate:'Candidato à mesma pauta'})[x.decision]||x.decision));for(const key of ['article_a','article_b']){const a=byId.get(String(x[key]));row.append(button(a?.title||x[key],()=>reader(x[key])));}row.append(n('p',`Título: ${x.title_similarity} · Início do texto: ${x.lead_similarity} · Sobreposição textual: ${x.lead_jaccard}`),raw(x));el.append(row);}};draw();}
async function init(){try{m=await get('manifest.json');let loaded=0;const chunks=[];for(let i=0;i<m.article_chunks.length;i+=8){const part=await Promise.all(m.article_chunks.slice(i,i+8).map(get));chunks.push(...part);loaded+=part.reduce((n,a)=>n+a.length,0);$('coverage').textContent=`Carregando a base inteira: ${num(loaded)} / ${num(m.total_articles)} matérias`;}articles=chunks.flat();byId=new Map(articles.map(a=>[String(a.id),a]));for(const [id,[label]] of Object.entries(sections)){const a=n('a',label);a.href='#'+id;$('engines').append(a);}render();}catch(e){$('results').replaceChildren(notice('Não foi possível carregar a base: '+e.message),button('Recarregar',()=>location.reload()));}}
$('close-reader').onclick=()=>$('reader').close();$('refresh').onclick=()=>location.reload();window.onhashchange=()=>{page=0;render();};init();
