const $=id=>document.getElementById(id),base=new URL('data/explorer/',location.href);
const n=(tag,text,cls)=>{const el=document.createElement(tag);if(text!=null)el.textContent=text;if(cls)el.className=cls;return el;};
const cache=new Map();async function get(file){if(!cache.has(file))cache.set(file,fetch(new URL(file,base)).then(r=>{if(!r.ok)throw Error(`Falha ao carregar ${file} (${r.status})`);return r.json();}).catch(e=>{cache.delete(file);throw e;}));return cache.get(file);}
function link(url,label){const el=n('a',label,'btn');try{const u=new URL(url,location.href);if(!['https:','http:'].includes(u.protocol))return n('span',label);el.href=u.href;}catch{return n('span',label);}el.target='_blank';el.rel='noopener noreferrer';return el;}
const button=(label,fn)=>{const b=n('button',label,'btn');b.type='button';b.onclick=fn;return b;};
function details(title,value){const d=n('details');d.append(n('summary',title),n('pre',JSON.stringify(value,null,2)));return d;}
let manifest,closure='',scope='globe',place='',status='matched',query='',page=0,version=0,byId=new Map();
function select(label,options,value,fn){const l=n('label',label),s=n('select',null,'form-select');for(const [v,t]of options){const o=n('option',t);o.value=v;s.append(o);}s.value=value;s.onchange=()=>{fn(s.value);page=0;render();};l.append(s);return l;}
function article(id){const a=byId.get(String(id));const row=n('div',null,'evidence-row');if(!a){row.append(n('p',`Matéria ${id} indisponível`));return row;}row.append(n('strong',a.title),n('p',(a.sources||[]).map(s=>`${s.name} · ${s.country}`).join(' / ')),link(a.url,'Abrir fonte'));const tr=new URL('https://translate.google.com/');tr.search=new URLSearchParams({sl:'auto',tl:'pt',text:a.title||'',op:'translate'});row.append(link(tr,'Traduzir título'));return row;}
function evidence(topic){const d=$('reader');$('reader-content').replaceChildren(n('h2',topic.label),n('p','Índices de similaridade; não são probabilidades de veracidade nem prova de confirmação independente.'));for(const pair of topic.evidence){const row=n('section',null,'card article');row.append(n('h3',pair.decision==='duplicate'?'Cópia estimada — não é confirmação independente':'Correspondência candidata — revisão pendente'),article(pair.street_id),article(pair.reference_id),n('p',`Título: ${pair.title_similarity} · Início do texto: ${pair.lead_similarity} · Sobreposição: ${pair.lead_jaccard}`));$('reader-content').append(row);}if(!topic.evidence.length)for(const id of topic.street_article_ids)$('reader-content').append(article(id));if(!d.open)d.showModal();}
function card(t){const c=n('article',null,'card article');c.append(n('h2',t.label),n('p',`${t.street_distinct_texts} textos distintos estimados na base · ${t.reference_distinct_texts} nas referências`),n('p',t.reference_sources.join(', ')||'Nenhuma correspondência observada neste corte'),n('p',`Participação: ${(t.street_share*100).toFixed(2)}% na base / ${(t.reference_share*100).toFixed(2)}% nas referências. Escopos editoriais diferentes.`));if(t.copy_links)c.append(n('p',`${t.copy_links} vínculos com cópias estimadas.`));c.append(button(t.evidence.length?`Ver ${t.evidence.length} comparações`:'Ver matérias da pauta',()=>evidence(t)));return c;}
async function render(){const ticket=++version,out=$('results'),bar=$('controls');out.replaceChildren(n('p','Carregando confronto…'));bar.replaceChildren();try{const closed=manifest.closures.filter(c=>c.mode==='closed');if(!closed.length){out.replaceChildren(n('p','Aguardando o primeiro fechamento diário.'));return;}if(!closure)closure=closed[0].id;bar.append(select('Dia fechado',closed.map(c=>[c.id,c.day]),closure,v=>{closure=v;place='';}));const c=closed.find(c=>c.id===closure);if(!c.reference_comparison){out.replaceChildren(n('p','O fechamento existe. O confronto com as 15 referências ainda está sendo preparado; nenhum resultado foi presumido.'));return;}const report=await get(c.reference_comparison);const places=await get(report.scope_files[scope]);if(ticket!==version)return;byId=new Map(report.articles.map(a=>[String(a.id),a]));if(!places[place])place=Object.keys(places)[0]||'';bar.append(select('Abrangência',[['globe','Mundo'],['continent','Continente'],['country','País']],scope,v=>{scope=v;place='';}),select('Local',Object.keys(places).map(p=>[p,p]),place,v=>place=v),select('Mostrar',[['matched','Com correspondência'],['unmatched','Sem correspondência observada'],['all','Todas as pautas'],['reference_only','Referências sem correspondência mundial']],status,v=>status=v));const label=n('label','Buscar pauta'),input=n('input',null,'form-control');input.value=query;input.type='search';label.append(input);bar.append(label,button('Aplicar busca',()=>{query=input.value;page=0;render();}));input.onkeydown=e=>{if(e.key==='Enter'){query=input.value;page=0;render();}};
$('coverage').textContent=`Dia ${report.day} · corte ${report.cutoff} · gerado ${report.generated_at}. Comparação semântica conservadora; revisão editorial pendente.`;
out.replaceChildren(n('p',`${report.counts.street_articles.toLocaleString('pt-BR')} publicações na base comparada · ${report.counts.reference_articles.toLocaleString('pt-BR')} nas referências · ${report.counts.matched_pairs} pares encontrados.`, 'notice'));
const coverage=n('details');coverage.append(n('summary','Cobertura das 15 referências'));for(const s of report.source_coverage){coverage.append(n('p',`${s.name}: ${s.day_articles} matérias / ${s.body_texts} textos · ${s.successful_slots}/${s.expected_day_and_closing_slots} rodadas documentadas com sucesso · ${s.coverage==='observed_slots_complete'?'rodadas observadas completas':'cobertura parcial ou não verificável'}`));}out.append(coverage,n('p','Falha de coleta ou ausência de correspondência não prova silêncio editorial. Uma mesma publicação não confirma a si própria. Divergências de opinião ainda não são inferidas.'),link(new URL(c.reference_comparison,base),'Baixar contrato e evidências'),link(new URL(report.scope_files[scope],base),'Baixar este escopo'),details('Método e limitações',report.method));
const q=query.trim().toLocaleLowerCase();let rows=status==='reference_only'?report.reference_without_match.map(id=>byId.get(String(id))).filter(Boolean):(places[place]?.topics||[]).filter(t=>status==='all'||(status==='matched'?t.status==='correspondence_found':t.status==='no_match_observed'));rows=rows.filter(t=>(t.label||t.title||'').toLocaleLowerCase().includes(q));if(page*30>=rows.length)page=0;out.append(n('p',`${rows.length} resultados · página ${page+1} de ${Math.max(1,Math.ceil(rows.length/30))}`));const nav=n('div',null,'actions');if(page)nav.append(button('Anterior',()=>{page--;render();}));if((page+1)*30<rows.length)nav.append(button('Próxima',()=>{page++;render();}));out.append(nav);const grid=n('div',null,'article-grid');for(const row of rows.slice(page*30,(page+1)*30))grid.append(status==='reference_only'?article(row.id):card(row));out.append(grid);out.setAttribute('aria-busy','false');}catch(e){if(ticket===version)out.replaceChildren(n('p',e.message),button('Tentar novamente',render));}}
$('title').textContent='Confronto · 15 referências';$('description').textContent='Fechamento diário × referências mundiais: país, continente e mundo';for(const [href,label]of [['index.html#overview','Visão geral'],['index.html#articles','Todas as matérias'],['index.html#daily','Fechamento diário'],['references.html','Confronto · 15 referências'],['index.html#operations','Coleta e erros']]){const a=n('a',label);a.href=href;$('engines').append(a);}
$('close-reader').onclick=()=>$('reader').close();$('refresh').onclick=()=>location.reload();try{manifest=await get('manifest.json');await render();}catch(e){$('results').replaceChildren(n('p',e.message));}
